//드라마, 일상, 개그, 로맨스, 무협, 스포츠, 액션, 스릴러, 판타지

export const webtoons = [
    {
        id:'mon1',
        title: '뷰티풀 군바리',
        day: '월',
        img:'../img/월1.jpg',
        url: 'https://comic.naver.com/webtoon/list?titleId=648419&weekday=mon',
        genre:'드라마',
    },
    {
        id:'mon2',
        title:'소녀의 세계',
        day:'월',
        img:'../img/월2.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=654774&weekday=mon',
        genre:'드라마',
    },{
        id:'mon3',
        title:'결혼생활 그림일기',
        day:'월',
        img:'../img/월3.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=741891&weekday=mon',
        genre:'일상',
    },{
        id:'mon4',
        title:'윈드브레이커',
        day:'월',
        img:'../img/월4.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=602910&weekday=mon',
        genre:'스포츠',
    },{
        id:'mon5',
        title:'똑 닮은 딸',
        day:'월',
        img:'../img/월5.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=774866&weekday=mon',
        genre:'스릴러',
    },{
        id:'mon6',
        title:'퍼니게임',
        day:'월',
        img:'../img/월6.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=801035&weekday=mon',
        genre:'스릴러',
    },{
        id:'mon7',
        title:'호랑신랑뎐',
        day:'월',
        img:'../img/월7.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=795643&weekday=mon',
        genre:'판타지',
    },{
        id:'mon8',
        title:'북부 공작님을 유혹하겠습니다',
        day:'월',
        img:'../img/월8.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=794421&weekday=mon',
        genre:'로맨스',
    },{
        id:'mon9',
        title:'히어로메이커',
        day:'월',
        img:'../img/월9.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=21815&weekday=mon',
        genre:'판타지',
    },{
        id:'mon10',
        title:'꼬리잡기',
        day:'월',
        img:'../img/월10.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=758666&weekday=mon',
        genre:'스릴러',
    },{
        id:'mon11',
        title:'루루라라 우리네 인생',
        day:'월',
        img:'../img/월11.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=802039&weekday=mon',
        genre:'일상',
    },{
        id:'mon12',
        title:'하루의 하루',
        day:'월',
        img:'../img/월12.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=774302&weekday=mon',
        genre:'드라마',
    },{
        id:'tue1',
        title:'마루는 강쥐',
        day:'화',
        img:'../img/화1.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=796152&weekday=tue',
        genre:'개그',
    },{
        id:'tue2',
        title:'집이 없어',
        day:'화',
        img:'../img/화2.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=721433&weekday=tue',
        genre:'드라마',
    },{
        id:'tue3',
        title:'호랑이 들어와요',
        day:'화',
        img:'../img/화3.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=757904&weekday=tue',
        genre:'판타지',
    },{
        id:'tue4',
        title:'위아더좀비',
        day:'화',
        img:'../img/화4.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=766648&weekday=tue',
        genre:'드라마',
    },{
        id:'tue5',
        title:'애옹식당',
        day:'화',
        img:'../img/화5.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=785703&weekday=tue',
        genre:'일상',
    },{
        id:'tue6',
        title:'대신 심부름을 해다오',
        day:'화',
        img:'../img/화6.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=769551&weekday=tue',
        genre:'드라마',
    },{
        id:'tue7',
        title:'내가 키운 S급들',
        day:'화',
        img:'../img/화7.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=784248&weekday=tue',
        genre:'판타지',
    },{
        id:'tue8',
        title:'용사가 돌아왔다',
        day:'화',
        img:'../img/화8.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=773459&weekday=tue',
        genre:'액션',
    },{
        id:'tue9',
        title:'하루만 네가 되고 싶어',
        day:'화',
        img:'../img/화9.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=738487&weekday=tue',
        genre:'로맨스',
    },{
        id:'tue10',
        title:'궤짝',
        day:'화',
        img:'../img/화10.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=802389&weekday=tue',
        genre:'스릴러',
    },{
        id:'tue11',
        title:'사신소년',
        day:'화',
        img:'../img/화11.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=730656&weekday=tue',
        genre:'액션',
    },{
        id:'tue12',
        title:'그냥 선생님',
        day:'화',
        img:'../img/화12.jpg',
        url:'https://comic.naver.com/webtoon/list?titleId=804333&weekday=tue',
        genre:'일상',
    },
]