//드라마, 일상, 개그, 로맨스, 무협/사극, 스포츠, 액션, 스릴러, 판타지

export const webtoons = [
  {
    id: 'mon1',
    title: '뷰티풀 군바리',
    day: ['월'],
    img: '../img/월1.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=648419&weekday=mon',
    genre: '드라마',
  },
  {
    id: 'mon2',
    title: '소녀의 세계',
    day: ['월'],
    img: '../img/월2.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=654774&weekday=mon',
    genre: '드라마',
  },
  {
    id: 'mon3',
    title: '결혼생활 그림일기',
    day: ['월'],
    img: '../img/월3.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=741891&weekday=mon',
    genre: '일상',
  },
  {
    id: 'mon4',
    title: '윈드브레이커',
    day: ['월'],
    img: '../img/월4.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=602910&weekday=mon',
    genre: '스포츠',
  },
  {
    id: 'mon5',
    title: '똑 닮은 딸',
    day: ['월'],
    img: '../img/월5.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=774866&weekday=mon',
    genre: '스릴러',
  },
  {
    id: 'mon6',
    title: '퍼니게임',
    day: ['월'],
    img: '../img/월6.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=801035&weekday=mon',
    genre: '스릴러',
  },
  {
    id: 'mon7',
    title: '호랑신랑뎐',
    day: ['월', '목'],
    img: '../img/월7.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=795643&weekday=mon',
    genre: '판타지',
  },
  {
    id: 'mon8',
    title: '북부 공작님을 유혹하겠습니다',
    day: ['월'],
    img: '../img/월8.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=794421&weekday=mon',
    genre: '로맨스',
  },
  {
    id: 'mon9',
    title: '히어로메이커',
    day: ['월'],
    img: '../img/월9.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=21815&weekday=mon',
    genre: '판타지',
  },
  {
    id: 'mon10',
    title: '꼬리잡기',
    day: ['월'],
    img: '../img/월10.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=758666&weekday=mon',
    genre: '스릴러',
  },
  {
    id: 'mon11',
    title: '루루라라 우리네 인생',
    day: ['월', '목'],
    img: '../img/월11.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=802039&weekday=mon',
    genre: '일상',
  },
  {
    id: 'mon12',
    title: '하루의 하루',
    day: ['월'],
    img: '../img/월12.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=774302&weekday=mon',
    genre: '드라마',
  },
  {
    id: 'mon13',
    title: '퀘스트지상주의',
    day: ['월'],
    img: '../img/월13.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783052&weekday=mon',
    genre: '드라마',
  },
  {
    id: 'mon14',
    title: '장씨세가 호위무사',
    day: ['월'],
    img: '../img/월14.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=728750&weekday=mon',
    genre: '무협',
  },
  {
    id: 'mon15',
    title: '참교육',
    day: ['월'],
    img: '../img/월15.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=758037&weekday=mon',
    genre: '액션',
  },
  {
    id: 'mon16',
    title: '팔이피플',
    day: ['월'],
    img: '../img/월16.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=774863&weekday=mon',
    genre: '드라마',
  },
  {
    id: 'mon17',
    title: '신화급 귀속 아이템을 손에 넣었다',
    day: ['월'],
    img: '../img/월17.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=795297&weekday=mon',
    genre: '판타지',
  },
  {
    id: 'mon18',
    title: '앵무살수',
    day: ['월'],
    img: '../img/월18.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=739115&weekday=mon',
    genre: '드라마',
  },
  {
    id: 'mon19',
    title: '버림받은 왕녀의 은밀한 침실',
    day: ['월'],
    img: '../img/월19.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=796867&weekday=mon',
    genre: '로맨스',
  },
  {
    id: 'mon20',
    title: '잔불의 기사',
    day: ['월'],
    img: '../img/월20.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=768536&weekday=mon',
    genre: '판타지',
  },
  {
    id: 'mon21',
    title: '신군',
    day: ['월'],
    img: '../img/월21.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783050&weekday=mon',
    genre: '액션',
  },
  {
    id: 'mon22',
    title: '물어보는 사이',
    day: ['월'],
    img: '../img/월22.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=772725&weekday=mon',
    genre: '로맨스',
  },
  {
    id: 'mon23',
    title: '원하나',
    day: ['월'],
    img: '../img/월23.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804469&weekday=mon',
    genre: '드라마',
  },
  {
    id: 'mon24',
    title: '순정말고 순종',
    day: ['월'],
    img: '../img/월24.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=761461&weekday=mon',
    genre: '로맨스',
  },
  {
    id: 'mon25',
    title: '강남의 기사',
    day: ['월'],
    img: '../img/월25.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=802865&weekday=mon',
    genre: '판타지',
  },
  {
    id: 'mon26',
    title: '악당과 악당이 만나면',
    day: ['월'],
    img: '../img/월26.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804782&weekday=mon',
    genre: '로맨스',
  },
  {
    id: 'mon27',
    title: '리턴 투 플레이어',
    day: ['월'],
    img: '../img/월27.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=752414&weekday=mon',
    genre: '판타지',
  },
  {
    id: 'mon28',
    title: '이별 후 사내 결혼',
    day: ['월'],
    img: '../img/월28.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=785253&weekday=mon',
    genre: '로맨스',
  },
  {
    id: 'mon29',
    title: '더블클릭',
    day: ['월'],
    img: '../img/월29.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=769663&weekday=mon',
    genre: '액션',
  },
  {
    id: 'mon30',
    title: '서브 남주가 파업하면 생기는 일',
    day: ['월'],
    img: '../img/월30.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=803518&weekday=mon',
    genre: '판타지',
  },
  {
    id: 'tue1',
    title: '마루는 강쥐',
    day: ['화'],
    img: '../img/화1.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=796152&weekday=tue',
    genre: '개그',
  },
  {
    id: 'tue2',
    title: '집이 없어',
    day: ['화'],
    img: '../img/화2.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=721433&weekday=tue',
    genre: '드라마',
  },
  {
    id: 'tue3',
    title: '호랑이 들어와요',
    day: ['화'],
    img: '../img/화3.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=757904&weekday=tue',
    genre: '판타지',
  },
  {
    id: 'tue4',
    title: '위아더좀비',
    day: ['화'],
    img: '../img/화4.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=766648&weekday=tue',
    genre: '드라마',
  },
  {
    id: 'tue5',
    title: '애옹식당',
    day: ['화'],
    img: '../img/화5.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=785703&weekday=tue',
    genre: '일상',
  },
  {
    id: 'tue6',
    title: '대신 심부름을 해다오',
    day: ['화'],
    img: '../img/화6.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=769551&weekday=tue',
    genre: '드라마',
  },
  {
    id: 'tue7',
    title: '내가 키운 S급들',
    day: ['화'],
    img: '../img/화7.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=784248&weekday=tue',
    genre: '판타지',
  },
  {
    id: 'tue8',
    title: '용사가 돌아왔다',
    day: ['화'],
    img: '../img/화8.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=773459&weekday=tue',
    genre: '액션',
  },
  {
    id: 'tue9',
    title: '하루만 네가 되고 싶어',
    day: ['화'],
    img: '../img/화9.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=738487&weekday=tue',
    genre: '로맨스',
  },
  {
    id: 'tue10',
    title: '궤짝',
    day: ['화'],
    img: '../img/화10.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=802389&weekday=tue',
    genre: '스릴러',
  },
  {
    id: 'tue11',
    title: '사신소년',
    day: ['화'],
    img: '../img/화11.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=730656&weekday=tue',
    genre: '액션',
  },
  {
    id: 'tue12',
    title: '그냥 선생님',
    day: ['화', '금'],
    img: '../img/화12.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804333&weekday=tue',
    genre: '일상',
  },
  {
    id: 'tue13',
    title: '김부장',
    day: ['화'],
    img: '../img/화13.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783053&weekday=tue',
    genre: '액션',
  },
  {
    id: 'tue14',
    title: '대학원 탈출일지',
    day: ['화'],
    img: '../img/화14.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=790713&weekday=tue',
    genre: '일상',
  },
  {
    id: 'tue15',
    title: '한림체육관',
    day: ['화'],
    img: '../img/화15.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=743139&weekday=tue',
    genre: '액션',
  },
  {
    id: 'tue16',
    title: '여신강림',
    day: ['화'],
    img: '../img/화16.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=703846&weekday=tue',
    genre: '로맨스',
  },
  {
    id: 'tue17',
    title: '사변괴담',
    day: ['화'],
    img: '../img/화17.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804783&weekday=tue',
    genre: '스릴러',
  },
  {
    id: 'tue18',
    title: '멸망 이후의 세계',
    day: ['화'],
    img: '../img/화18.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=789979&weekday=tue',
    genre: '판타지',
  },
  {
    id: 'tue19',
    title: '놓지마 정신줄 시즌3',
    day: ['화'],
    img: '../img/화19.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=801589&weekday=tue',
    genre: '개그',
  },
  {
    id: 'tue20',
    title: '헬58',
    day: ['화'],
    img: '../img/화20.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=719508&weekday=tue',
    genre: '액션',
  },
  {
    id: 'tue21',
    title: '하북팽가 막내아들',
    day: ['화'],
    img: '../img/화21.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783877&weekday=tue',
    genre: '무협',
  },
  {
    id: 'tue22',
    title: '삼국지톡',
    day: ['화', '금'],
    img: '../img/화22.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=711422&weekday=tue',
    genre: '사극',
  },
  {
    id: 'tue23',
    title: '천마는 평범하게 살 수 없다',
    day: ['화'],
    img: '../img/화23.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=774358&weekday=tue',
    genre: '판타지',
  },
  {
    id: 'tue24',
    title: '악몽의 형상',
    day: ['화'],
    img: '../img/화24.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=793283&weekday=tue',
    genre: '스릴러',
  },
  {
    id: 'tue25',
    title: '유사연애',
    day: ['화'],
    img: '../img/화25.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804653&weekday=tue',
    genre: '로맨스',
  },
  {
    id: 'tue26',
    title: '랜덤채팅의 그녀!',
    day: ['화'],
    img: '../img/화26.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=702608&weekday=tue',
    genre: '드라마',
  },
  {
    id: 'tue27',
    title: '원주민 공포만화',
    day: ['화'],
    img: '../img/화27.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=698918&weekday=tue',
    genre: '스릴러',
  },
  {
    id: 'tue28',
    title: '초인의 게임',
    day: ['화'],
    img: '../img/화28.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=795658&weekday=tue',
    genre: '판타지',
  },
  {
    id: 'tue29',
    title: '시한부인 줄 알았어요!',
    day: ['화'],
    img: '../img/화29.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=801711&weekday=tue',
    genre: '로맨스',
  },
  {
    id: 'tue30',
    title: '저 그런 인재 아닙니다',
    day: ['화'],
    img: '../img/화30.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=802840&weekday=tue',
    genre: '판타지',
  },
  {
    id: 'wed1',
    title: '내 남편과 결혼해줘',
    day: ['수'],
    img: '../img/wed01.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783769&weekday=wed',
    genre: '로맨스',
  },
  {
    id: 'wed2',
    title: '전지적 독자 시점',
    day: ['수'],
    img: '../img/wed02.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=747269&weekday=wed',
    genre: '판타지',
  },
  {
    id: 'wed3',
    title: '헬퍼 2 : 킬베로스',
    day: ['수'],
    img: '../img/wed03.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=670143&weekday=wed',
    genre: '액션',
  },
  {
    id: 'wed4',
    title: '일렉시드',
    day: ['수'],
    img: '../img/wed04.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=717481&weekday=wed',
    genre: '액션',
  },
  {
    id: 'wed5',
    title: '66666년 만에 환생한 흑마법사',
    day: ['수'],
    img: '../img/wed05.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=775141&weekday=wed',
    genre: '판타지',
  },
  {
    id: 'wed6',
    title: '격기3반',
    day: ['수'],
    img: '../img/wed06.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=701535&weekday=wed',
    genre: '스포츠',
  },
  {
    id: 'wed7',
    title: '나쁜사람',
    day: ['수'],
    img: '../img/wed07.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=750184&weekday=wed',
    genre: '액션',
  },
  {
    id: 'wed8',
    title: '튜토리얼 탑의 고인물',
    day: ['수'],
    img: '../img/wed08.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=738694&weekday=wed',
    genre: '액션',
  },
  {
    id: 'wed9',
    title: '무림서부',
    day: ['수'],
    img: '../img/wed09.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=784417&weekday=wed',
    genre: '무협',
  },
  {
    id: 'wed10',
    title: '급식아빠',
    day: ['수'],
    img: '../img/wed10.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=758662&weekday=wed',
    genre: '액션',
  },
  {
    id: 'wed11',
    title: '연놈',
    day: ['수'],
    img: '../img/wed11.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=667573&weekday=wed',
    genre: '드라마',
  },
  {
    id: 'wed12',
    title: '내가 죽기로 결심한 것은',
    day: ['수'],
    img: '../img/wed12.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783523&weekday=wed',
    genre: '로맨스',
  },
  {
    id: 'wed13',
    title: '마른 가지에 바람처럼',
    day: ['수'],
    img: '../img/wed13.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=748535&weekday=wed',
    genre: '로맨스',
  },
  {
    id: 'wed14',
    title: '칼에 취한 밤을 걷다',
    day: ['수'],
    img: '../img/wed14.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=795542&weekday=wed',
    genre: '무협/사극',
  },
  {
    id: 'wed15',
    title: '빌드업',
    day: ['수'],
    img: '../img/wed15.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=750826&weekday=wed',
    genre: '스포츠',
  },
  {
    id: 'wed16',
    title: '운명을 보는 회사원',
    day: ['수'],
    img: '../img/wed16.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=797443&weekday=wed',
    genre: '판타지',
  },
  {
    id: 'wed17',
    title: '행성인간2: 행성의',
    day: ['수'],
    img: '../img/wed17.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=802940&weekday=wed',
    genre: '스릴러',
  },
  {
    id: 'wed18',
    title: '사상최강',
    day: ['수'],
    img: '../img/wed18.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=748536&weekday=wed',
    genre: '무협/사극',
  },
  {
    id: 'wed19',
    title: '안녕, 나의 수집',
    day: ['수'],
    img: '../img/wed19.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=799267&weekday=wed',
    genre: '일상',
  },
  {
    id: 'wed20',
    title: '고삼무쌍',
    day: ['수'],
    img: '../img/wed20.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=728126&weekday=wed',
    genre: '액션',
  },
  {
    id: 'wed21',
    title: '세상은 돈과 권력',
    day: ['수'],
    img: '../img/wed21.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=710747&weekday=wed',
    genre: '드라마',
  },
  {
    id: 'wed22',
    title: '베스트 프렌드',
    day: ['수'],
    img: '../img/wed22.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=789434&weekday=wed',
    genre: '스릴러',
  },
  {
    id: 'wed23',
    title: '에브리띵 이즈 파인',
    day: ['수'],
    img: '../img/wed23.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804145&weekday=wed',
    genre: '스릴러',
  },
  {
    id: 'wed24',
    title: '굿헌팅',
    day: ['수'],
    img: '../img/wed24.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804989&weekday=wed',
    genre: '스릴러',
  },
  {
    id: 'wed25',
    title: '황후를 훔친 이는 누구인가',
    day: ['수'],
    img: '../img/wed25.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805737&weekday=wed',
    genre: '일상',
  },
  {
    id: 'wed26',
    title: '판타지 여동생!',
    day: ['수'],
    img: '../img/wed26.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=730425&weekday=wed',
    genre: '판타지',
  },
  {
    id: 'wed27',
    title: '이십팔세기 광팬',
    day: ['수'],
    img: '../img/wed27.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=800312&weekday=wed',
    genre: '개그',
  },
  {
    id: 'wed28',
    title: '칼부림',
    day: ['수'],
    img: '../img/wed28.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=602916&weekday=wed',
    genre: '무협/사극',
  },
  {
    id: 'wed29',
    title: '물고기로 살아남기',
    day: ['수'],
    img: '../img/wed29.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=793887&weekday=wed',
    genre: '판타지',
  },
  {
    id: 'wed30',
    title: '히어로 더 맥시멈',
    day: ['수'],
    img: '../img/wed30.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805323&weekday=wed',
    genre: '액션',
  },
  {
    id: 'thu1',
    title: '재벌집 막내아들',
    day: ['목'],
    img: '../img/thu01.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=800770&weekday=thu',
    genre: '드라마',
  },
  {
    id: 'thu2',
    title: '앞집나리',
    day: ['목'],
    img: '../img/thu02.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=802293&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu3',
    title: '연애혁명',
    day: ['목'],
    img: '../img/thu03.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=570503&weekday=thu',
    genre: '드라마',
  },
  {
    id: 'thu4',
    title: '나노마신',
    day: ['목'],
    img: '../img/thu04.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=747271&weekday=thu',
    genre: '무협',
  },
  {
    id: 'thu5',
    title: '남편을 죽여줘요',
    day: ['목'],
    img: '../img/thu05.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=797410&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu6',
    title: '천마육성',
    day: ['목'],
    img: '../img/thu06.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=776255&weekday=thu',
    genre: '무협',
  },
  {
    id: 'thu7',
    title: '나 혼자 네크로맨서',
    day: ['목'],
    img: '../img/thu07.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=780170&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'thu8',
    title: '현실퀘스트',
    day: ['목'],
    img: '../img/thu08.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783888&weekday=thu',
    genre: '액션',
  },
  {
    id: 'thu9',
    title: '회귀한 천재 헌터의 슬기로운 청소생활',
    day: ['목'],
    img: '../img/thu09.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=796827&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'thu10',
    title: '무사만리행',
    day: ['목'],
    img: '../img/thu10.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=746857&weekday=thu',
    genre: '무협',
  },
  {
    id: 'thu11',
    title: '보스였음',
    day: ['목'],
    img: '../img/thu11.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=802833&weekday=thu',
    genre: '액션',
  },
  {
    id: 'thu13',
    title: '노답소녀',
    day: ['목'],
    img: '../img/thu13.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=756137&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu14',
    title: '별을 삼킨 너에게',
    day: ['목'],
    img: '../img/thu14.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=748831&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu15',
    title: '뮤즈 온 유명',
    day: ['목'],
    img: '../img/thu15.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=801505&weekday=thu',
    genre: '드라마',
  },
  {
    id: 'thu16',
    title: '순정빌런',
    day: ['목'],
    img: '../img/thu16.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=797731&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu17',
    title: '버려진 나의 최애를 위하여',
    day: ['목'],
    img: '../img/thu17.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=794155&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu18',
    title: '쿠베라',
    day: ['목'],
    img: '../img/thu18.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=131385&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'thu19',
    title: '국세청 망나니',
    day: ['목'],
    img: '../img/thu19.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=785727&weekday=thu',
    genre: '드라마',
  },
  {
    id: 'thu20',
    title: '규격 외 혈통 천재',
    day: ['목'],
    img: '../img/thu20.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=798331&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'thu21',
    title: '특수청소',
    day: ['목'],
    img: '../img/thu21.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=788976&weekday=thu',
    genre: '드라마',
  },
  {
    id: 'thu22',
    title: '최강전설 강해효',
    day: ['목'],
    img: '../img/thu22.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=570506&weekday=thu',
    genre: '액션',
  },
  {
    id: 'thu23',
    title: '꽃만 키우는데 너무강함',
    day: ['목'],
    img: '../img/thu23.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=741825&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'thu24',
    title: '던전 씹어먹는 아티팩트',
    day: ['목'],
    img: '../img/thu24.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=758439&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'thu25',
    title: '이러면 안 돼요, 전하!',
    day: ['목'],
    img: '../img/thu25.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805368&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu26',
    title: '이게 웬 떡',
    day: ['목'],
    img: '../img/thu26.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804051&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu27',
    title: '만능잡캐',
    day: ['목'],
    img: '../img/thu27.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783117&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'thu28',
    title: '흑막 여주가 날 새엄마로 만들려고 해',
    day: ['목'],
    img: '../img/thu28.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=770523&weekday=thu',
    genre: '로맨스',
  },
  {
    id: 'thu29',
    title: '누나! 나 무서워',
    day: ['목'],
    img: '../img/thu29.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=797468&weekday=thu',
    genre: '스릴러',
  },
  {
    id: 'thu30',
    title: '마왕까지 한 걸음',
    day: ['목'],
    img: '../img/thu30.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=776668&weekday=thu',
    genre: '판타지',
  },
  {
    id: 'fri1',
    title: '외모지상주의',
    day: ['금'],
    img: '../img/fri1.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=641253&weekday=fri',
    genre: '드라마',
  },
  {
    id: 'fri2',
    title: '더 게이머',
    day: ['금'],
    img: '../img/fri2.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=552960&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri3',
    title: '나 혼자 만렙 뉴비',
    day: ['금'],
    img: '../img/fri3.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=773797&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri4',
    title: '어쩌다보니 천생연분',
    day: ['금'],
    img: '../img/fri4.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=790245&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'fri5',
    title: '개를 낳았다',
    day: ['금'],
    img: '../img/fri5.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=712362&weekday=fri',
    genre: '드라마',
  },
  {
    id: 'fri6',
    title: '1초',
    day: ['금'],
    img: '../img/fri6.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=725586&weekday=fri',
    genre: '드라마',
  },
  {
    id: 'fri7',
    title: '데드퀸',
    day: ['금'],
    img: '../img/fri7.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=753478&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri8',
    title: '역대급 영지 설계자',
    day: ['금'],
    img: '../img/fri8.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=777767&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri9',
    title: '대학원 탈출일지',
    day: ['금'],
    img: '../img/fri9.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=790713&weekday=fri',
    genre: '일상',
  },
  {
    id: 'fri10',
    title: '몽홀',
    day: ['금'],
    img: '../img/fri10.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=644112&weekday=fri',
    genre: '무협/사극',
  },
  {
    id: 'fri11',
    title: '낙향문사전',
    day: ['금'],
    img: '../img/fri11.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=746534&weekday=fri',
    genre: '무협/사극',
  },
  {
    id: 'fri12',
    title: '상남자',
    day: ['금'],
    img: '../img/fri12.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=751168&weekday=fri',
    genre: '드라마',
  },
  {
    id: 'fri13',
    title: '언니, 이번 생엔 내가 왕비야',
    day: ['금'],
    img: '../img/fri13.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=798917&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'fri14',
    title: '히어로 킬러',
    day: ['금'],
    img: '../img/fri14.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=766563&weekday=fri',
    genre: '액션',
  },
  {
    id: 'fri15',
    title: '사신',
    day: ['금'],
    img: '../img/fri15.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=799837&weekday=fri',
    genre: '무협/사극',
  },
  {
    id: 'fri16',
    title: '서울역 드루이드',
    day: ['금'],
    img: '../img/fri16.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=773476&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri17',
    title: '세기말 풋사과 보습학원',
    day: ['금'],
    img: '../img/fri17.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=761722&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'fri18',
    title: '커플 브레이커',
    day: ['금'],
    img: '../img/fri18.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804832&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'fri19',
    title: '전남편의 미친개를 길들였다',
    day: ['금'],
    img: '../img/fri19.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804160&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'fri20',
    title: '그렇고 그런 바람에',
    day: ['금'],
    img: '../img/fri20.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=783527&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'fri21',
    title: 'A.I. 닥터',
    day: ['금'],
    img: '../img/fri21.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=765804&weekday=fri',
    genre: '드라마',
  },
  {
    id: 'fri22',
    title: '더 게이머',
    day: ['금'],
    img: '../img/fri22.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=552960&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri23',
    title: '뫼신 사냥꾼',
    day: ['금'],
    img: '../img/fri23.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=751208&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri24',
    title: '언다잉',
    day: ['금'],
    img: '../img/fri24.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=801555&weekday=fri',
    genre: '스릴러',
  },
  {
    id: 'fri25',
    title: '대위님! 이번 전쟁터는 이곳인가요?',
    day: ['금'],
    img: '../img/fri25.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=803767&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'fri26',
    title: '브레이커 : 이터널 포스',
    day: ['금'],
    img: '../img/fri26.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=794383&weekday=fri',
    genre: '액션',
  },
  {
    id: 'fri27',
    title: '신컨의 원코인 클리어',
    day: ['금'],
    img: '../img/fri27.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805658&weekday=fri',
    genre: '판타지',
  },
  {
    id: 'fri28',
    title: '바스티안',
    day: ['금'],
    img: '../img/fri28.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805203&weekday=fri',
    genre: '로맨스',
  },
  {
    id: 'sat1',
    title: '호랑이형님',
    day: ['토'],
    img: '../img/sat1.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=650305&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat2',
    title: '프리드로우',
    day: ['토'],
    img: '../img/sat2.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=597447&weekday=sat',
    genre: '드라마',
  },
  {
    id: 'sat3',
    title: '99강화나무몽둥이',
    day: ['토'],
    img: '../img/sat3.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=792651&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat4',
    title: '취사병 전설이 되다',
    day: ['토'],
    img: '../img/sat4.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=727188&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat5',
    title: '나이트런',
    day: ['토'],
    img: '../img/sat5.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=64997&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat6',
    title: '윌유메리미',
    day: ['토'],
    img: '../img/sat6.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=616239&weekday=sat',
    genre: '일상',
  },
  {
    id: 'sat7',
    title: '스터디그룹',
    day: ['토'],
    img: '../img/sat7.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=721948&weekday=sat',
    genre: '액션',
  },
  {
    id: 'sat8',
    title: '놓지마 정신줄 시즌3',
    day: ['토'],
    img: '../img/sat8.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=801589&weekday=sat',
    genre: '개그',
  },
  {
    id: 'sat9',
    title: '어글리후드',
    day: ['토'],
    img: '../img/sat9.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=703630&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat10',
    title: '아홉수 우리들',
    day: ['토'],
    img: '../img/sat10.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=724815&weekday=sat',
    genre: '로맨스',
  },
  {
    id: 'sat11',
    title: '은탄',
    day: ['토'],
    img: '../img/sat11.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=787500&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat12',
    title: '나랑X할래?',
    day: ['토'],
    img: '../img/sat12.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=803934&weekday=sat',
    genre: '로맨스',
  },
  {
    id: 'sat13',
    title: '작전명 순정',
    day: ['토'],
    img: '../img/sat13.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=793275&weekday=sat',
    genre: '로맨스',
  },
  {
    id: 'sat14',
    title: '나이트런',
    day: ['토'],
    img: '../img/sat14.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=64997&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat15',
    title: '이종 격투기',
    day: ['토'],
    img: '../img/sat15.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805356&weekday=sat',
    genre: '드라마',
  },
  {
    id: 'sat16',
    title: '윌유메리미',
    day: ['토'],
    img: '../img/sat16.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=616239&weekday=sat',
    genre: '일상',
  },
  {
    id: 'sat17',
    title: '청춘 블라썸',
    day: ['토'],
    img: '../img/sat17.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=746834&weekday=sat',
    genre: '로맨스',
  },
  {
    id: 'sat18',
    title: '디펜스 게임의 폭군이 되었다',
    day: ['토'],
    img: '../img/sat18.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=798182&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat19',
    title: '민간인 통제구역 - 일급기밀',
    day: ['토'],
    img: '../img/sat19.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=801324&weekday=sat',
    genre: '스릴러',
  },
  {
    id: 'sat20',
    title: '반드시 해피엔딩',
    day: ['토'],
    img: '../img/sat20.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=769568&weekday=sat',
    genre: '로맨스',
  },
  {
    id: 'sat21',
    title: '이십팔세기 광팬',
    day: ['토'],
    img: '../img/sat21.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=800312&weekday=sat',
    genre: '개그',
  },
  {
    id: 'sat22',
    title: '물위의 우리',
    day: ['토'],
    img: '../img/sat22.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=780404&weekday=sat',
    genre: '드라마',
  },
  {
    id: 'sat23',
    title: '나를 바꿔줘',
    day: ['토'],
    img: '../img/sat23.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=733280&weekday=sat',
    genre: '드라마',
  },
  {
    id: 'sat24',
    title: '소공녀 민트',
    day: ['토'],
    img: '../img/sat24.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=787061&weekday=sat',
    genre: '드라마',
  },
  {
    id: 'sat25',
    title: '존잘주의',
    day: ['토'],
    img: '../img/sat25.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=774864&weekday=sat',
    genre: '로맨스',
  },
  {
    id: 'sat26',
    title: '남편 먹는 여자',
    day: ['토'],
    img: '../img/sat26.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=794154&weekday=sat',
    genre: '드라마',
  },
  {
    id: 'sat27',
    title: '어글리후드',
    day: ['토'],
    img: '../img/sat27.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=703630&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sat28',
    title: '마나 이퀄',
    day: ['토'],
    img: '../img/sat28.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=793350&weekday=sat',
    genre: '액션',
  },
  {
    id: 'sat29',
    title: '간첩 18세',
    day: ['토'],
    img: '../img/sat29.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=799503&weekday=sat',
    genre: '액션',
  },
  {
    id: 'sat30',
    title: '도사 가온',
    day: ['토'],
    img: '../img/sat30.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=733277&weekday=sat',
    genre: '판타지',
  },
  {
    id: 'sun1',
    title: '약한영웅',
    day: ['일'],
    img: '../img/sun1.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=710751&weekday=sun',
    genre: '액션',
  },
  {
    id: 'sun2',
    title: '싸움독학',
    day: ['일'],
    img: '../img/sun2.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=736277&weekday=sun',
    genre: '액션',
  },
  {
    id: 'sun3',
    title: '입학용병',
    day: ['일'],
    img: '../img/sun3.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=758150&weekday=sun',
    genre: '액션',
  },
  {
    id: 'sun4',
    title: '사형소년',
    day: ['일'],
    img: '../img/sun4.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=795262&weekday=sun',
    genre: '스릴러',
  },
  {
    id: 'sun5',
    title: '노빠꾸 최하영',
    day: ['일'],
    img: '../img/sun5.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=803480&weekday=sun',
    genre: '액션',
  },
  {
    id: 'sun6',
    title: '시월드가 내게 집착한다',
    day: ['일'],
    img: '../img/sun6.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=785251&weekday=sun',
    genre: '로맨스',
  },
  {
    id: 'sun7',
    title: '소녀재판',
    day: ['일'],
    img: '../img/sun7.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=743838&weekday=sun',
    genre: '드라마',
  },
  {
    id: 'sun8',
    title: '가비지타임',
    day: ['일'],
    img: '../img/sun8.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=703844&weekday=sun',
    genre: '스포츠',
  },
  {
    id: 'sun9',
    title: '키미앤조이',
    day: ['일'],
    img: '../img/sun9.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=798177&weekday=sun',
    genre: '로맨스',
  },
  {
    id: 'sun10',
    title: '샤인 스타',
    day: ['일'],
    img: '../img/sun10.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=758665&weekday=sun',
    genre: '로맨스',
  },
  {
    id: 'sun11',
    title: '나 혼자 특성빨로 무한 성장',
    day: ['일'],
    img: '../img/sun11.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=803909&weekday=sun',
    genre: '액션',
  },
  {
    id: 'sun12',
    title: '수희0(tngmlek0)',
    day: ['일'],
    img: '../img/sun12.jpg',
    url: 'https://comic.naver.com/webtoon/list?titleId=774831&weekday=sun',
    genre: '드라마',
  },
  {
    id: 'sun13',
    title: '천하제일인',
    day: ['일'],
    img: '../img/sun13.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=751207&weekday=sun',
    genre: '무협/사극',
  },
  {
    id: 'sun14',
    title: '천화서고 대공자',
    day: ['일'],
    img: '../img/sun14.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805193&weekday=sun',
    genre: '무협/사극',
  },
  {
    id: 'sun16',
    title: '고양이 타타',
    day: ['일'],
    img: '../img/sun16.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=805156&weekday=sun',
    genre: '드라마',
  },
  {
    id: 'sun17',
    title: '자매전쟁',
    day: ['일'],
    img: '../img/sun17.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=798664&weekday=sun',
    genre: '드라마',
  },
  {
    id: 'sun18',
    title: '안녕, 나의 수집',
    day: ['일'],
    img: '../img/sun18.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=799267&weekday=sun',
    genre: '일상',
  },
  {
    id: 'sun19',
    title: '소녀재판',
    day: ['일'],
    img: '../img/sun19.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=743838&weekday=sun',
    genre: '드라마',
  },
  {
    id: 'sun20',
    title: '판사 이한영',
    day: ['일'],
    img: '../img/sun20.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=759567&weekday=sun',
    genre: '드라마',
  },
  {
    id: 'sun21',
    title: '아포크리파',
    day: ['일'],
    img: '../img/sun21.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=804055&weekday=sun',
    genre: '스릴러',
  },
  {
    id: 'sun22',
    title: '분신으로 자동사냥',
    day: ['일'],
    img: '../img/sun22.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=799805&weekday=sun',
    genre: '판타지',
  },
  {
    id: 'sun23',
    title: '아카데미에 위장취업당했다',
    day: ['일'],
    img: '../img/sun23.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=795529&weekday=sun',
    genre: '판타지',
  },
  {
    id: 'sun24',
    title: '내일',
    day: ['일'],
    img: '../img/sun24.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=695796&weekday=sun',
    genre: '드라마',
  },
  {
    id: 'sun25',
    title: '살아남은 로맨스',
    day: ['일'],
    img: '../img/sun25.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=764129&weekday=sun',
    genre: '판타지',
  },
  {
    id: 'sun26',
    title: '밤마다 남편이 바뀐다',
    day: ['일'],
    img: '../img/sun26.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=803649&weekday=sun',
    genre: '로맨스',
  },
  {
    id: 'sun27',
    title: '마법스크롤 상인 지오',
    day: ['일'],
    img: '../img/sun27.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=655746&weekday=sun',
    genre: '판타지',
  },
  {
    id: 'sun28',
    title: '이세계 용사가 지구를 구하는 이유',
    day: ['일'],
    img: '../img/sun28.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=803222&weekday=sun',
    genre: '판타지',
  },
  {
    id: 'sun29',
    title: '폰투스 : 극야2',
    day: ['일'],
    img: '../img/sun29.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=792694&weekday=sun',
    genre: '스릴러',
  },
  {
    id: 'sun30',
    title: '무서운게 딱좋아!',
    day: ['일'],
    img: '../img/sun30.jpeg',
    url: 'https://comic.naver.com/webtoon/list?titleId=778322&weekday=sun',
    genre: '스릴러',
  },
];
